version: '2'
jobs:
  unit_tests:
    docker:
      - image: themattrix/tox
    working_directory: /opt/code
    steps:
      - checkout
      - run:
          name: Run basic tests
          working_directory: /opt/code
          command: tox -e py27,py35,py36,flake8
  integration_tests:
    machine:
      image: circleci/classic:201711-01
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Pull in kong-plugin-signalfx
          command: git submodule update --init --recursive --remote
      - run:
          name: Install dependencies
          command: |
            sudo apt update && sudo apt install -yq python3-pip
            pyenv local 3.5.2
            pip3 install tox
      - run:
          name: Run integration tests
          working_directory: ~/code
          command: tox -e integration
workflows:
  version: 2
  testing:
    jobs:
     - unit_tests
     - integration_tests
